server:
  port: 2000

spring:
  application:
    name: pig-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jieblog/pig-config.git
    bus:
      trace:
        enabled: true
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/

